apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mk6960xdn-python
  janus-idp.io/tekton: mk6960xdn-python
  backstage.io/kubernetes-id: mk6960xdn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mk6960xdn-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
