apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mk6960xdn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mk6960xdn-python 
  name: mk6960xdn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mk6960xdn-python 
