apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mk6960xdn-python 
  janus-idp.io/tekton: mk6960xdn-python
  backstage.io/kubernetes-id: mk6960xdn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mk6960xdn-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  